### ISSUE TITLE
svelte-fusioncharts not found in NPM 

### ISSUE THREAD

**Issue by jcollum** [fusioncharts/svelte-fusioncharts#3]
```
✗ npm install --save svelte-fusioncharts

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/svelte-fusioncharts - Not found
npm ERR! 404 
npm ERR! 404  'svelte-fusioncharts@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**Comment by priyanjitdey94** [comment]
@jcollum Hey, this is not yet published in npm. This is still a work in progress. Right now we are working on the documentation. We will be publishing in this week. Will let you know.

**Comment by priyanjitdey94** [comment]
@jcollum We have published in npm. You'll be able to download it now. You can refer to the [samples](https://fusioncharts.github.io/svelte-fusioncharts/) while creating charts.

Closing this ticket.
