### ISSUE TITLE
No Customize Theme in Svelte?

### ISSUE THREAD

**Issue by hmmhmmhm** [fusioncharts/svelte-fusioncharts#4]
I'm trying to change the color in the chart, but in this library, it's too complicated to change the theme

I just want to make the background to transparent, and change the color of the label, but is there any way I can change it quickly?

**Comment by priyanjitdey94** [comment]
Hey.

1. Changing background to transparent
`bgColor` and `bgAlpha` attributes can be used to change the background of the chart.
```
{
  "chart": {
    ...
    "bgColor": "#ff0000",
    "bgAlpha": "70",
     ...
  }
}
```

2. Changing the label color
Not sure which label is meant here. There are data-labels, axis-labels. They can be changed using certain attributes. For example, in Area chart, data label color can be changed by using the `valueFontColor` attribute. You can check [this](https://www.fusioncharts.com/dev/chart-attributes/area2d) link to explore all the attributes.

**Comment by priyanjitdey94** [comment]
@hmmhmmhm Hey. Did that solve your problem?

**Comment by hmmhmmhm** [comment]
Yup Thanks
